WITH EJERCICIO_CTE(ID, IDPROVINCIA, IDCANTON, IDPARROQUIA, CODIGO, DIVISION,NOMBRE, NIVEL) AS 
( 
    SELECT 
        d.SECUENCIAL AS ID, 
        d.SECUENCIAL AS IDPROVINCIA,
        NULL AS IDCANTON,
        NULL AS IDPARROQUIA,
        d.CODIGO ,
        CASE 
            WHEN d.SECUENCIALNIVEL = 4 THEN CONVERT(VARCHAR(10),'PROVINCIA')
        END AS DIVISION,
        D.NOMBRE,
        0 AS NIVEL 
    FROM FBS_GENERALES.DIVISION d
    WHERE d.SECUENCIALNIVEL IN (4)
    
    UNION ALL
    
    SELECT 
        P.SECUENCIALDIVISION AS ID,
       	EC.IDPROVINCIA AS IDPROVINCIA,
       	d.SECUENCIAL  AS IDCANTON,
       	NULL AS IDPARROQUIA,
        EC.CODIGO ,
        CASE 
            WHEN d.SECUENCIALNIVEL = 5 THEN CONVERT(VARCHAR(10), 'CANTON') 
        END AS DIVISION,
        D.NOMBRE,
        (NIVEL + 1) AS NIVEL
    FROM 
        EJERCICIO_CTE EC 
    INNER JOIN 
        FBS_GENERALES.PADREDIVISION P ON P.SECUENCIALDIVISIONPADRE = EC.ID
    INNER JOIN 
        FBS_GENERALES.DIVISION D ON D.SECUENCIAL = P.SECUENCIALDIVISION
    WHERE D.SECUENCIALNIVEL IN (5)
    
    UNION ALL
    
    SELECT 
        P.SECUENCIALDIVISION AS ID,
       	EC.IDPROVINCIA AS IDPROVINCIA,
       	EC.IDCANTON AS IDCANTON,
       	P.SECUENCIALDIVISION AS IDPARROQUIA,
        EC.CODIGO,
        CASE 
            WHEN d.SECUENCIALNIVEL = 6 THEN CONVERT(VARCHAR(10), 'PARROQUIA') 
        END AS DIVISION,
        D.NOMBRE,
        (NIVEL + 1) AS NIVEL
    FROM 
        EJERCICIO_CTE EC 
    INNER JOIN 
        FBS_GENERALES.PADREDIVISION P ON P.SECUENCIALDIVISIONPADRE = EC.ID
    INNER JOIN 
        FBS_GENERALES.DIVISION D ON D.SECUENCIAL = P.SECUENCIALDIVISION
    WHERE D.SECUENCIALNIVEL IN (6)
)
SELECT 
	ID,
    CODIGO,
    NIVEL,
    DIVISION,
    NOMBRE
FROM 
    EJERCICIO_CTE

ORDER BY 
    IDPROVINCIA, IDCANTON, IDPARROQUIA;
